version: '3.8'
name: "docusaurus"

services:
  dev:
    build:
      context: .
      target: dev
    container_name: docusaurus_local
    ports:
      - "3000:3000"      
    volumes:
      - .:/opt/docusaurus
      - ./../readmes:/opt/docusaurus/docs
    environment:
      - NODE_ENV=development

  serve: # TODO: fix issues
    build:
      context: .
      target: serve
    container_name: docusaurus
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  caddy: # TODO: fix issues
    build:
      context: .
      target: caddy
    container_name: docusaurus_caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - DOCUSAURUS_DOMAIN=docusaurus.example
      - DOCUSAURUS_EMAIL=letsencrypt@docusaurus.example
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: